# Generated by Django 5.0.6 on 2024-11-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('elements', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='images',
            field=models.ManyToManyField(blank=True, to='elements.image'),
        ),
    ]
