# Generated by Django 5.0.6 on 2025-01-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Title'),
        ),
    ]
