# Generated by Django 5.0.6 on 2024-10-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Announcement',
            name='source_name',
            field=models.CharField(verbose_name="Source name", max_length=100, null=True, blank=True)
        )
    ]
