# Generated by Django 5.0.6 on 2024-10-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='term',
        ),
    ]
