# Generated by Django 5.0.6 on 2024-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_remove_announcement_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
